# Generated by Django 3.2.3 on 2021-05-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('search_result_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=100)),
                ('results_total', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('ip_adress', models.GenericIPAddressField()),
            ],
        ),
    ]
