# Generated by Django 3.2.3 on 2021-05-29 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
