# Generated by Django 3.2.3 on 2021-05-29 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serp_app', '0002_alter_searchresult_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchresult',
            old_name='ip_adress',
            new_name='client_ip',
        ),
    ]
