# Generated by Django 3.2.3 on 2021-05-29 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serp_app', '0003_rename_ip_adress_searchresult_client_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresult',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
