# Generated by Django 3.2.3 on 2021-05-29 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serp_app', '0004_auto_20210529_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link_with_position',
            fields=[
                ('link_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=150)),
                ('position', models.IntegerField()),
                ('search_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serp_app.searchresult')),
            ],
        ),
    ]
