# Generated by Django 3.2.3 on 2021-05-29 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serp_app', '0005_link_with_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularWord',
            fields=[
                ('word_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('search_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serp_app.searchresult')),
            ],
        ),
    ]
