# Generated by Django 3.2.3 on 2021-06-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serp_app', '0006_popularword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularword',
            old_name='position',
            new_name='occurances',
        ),
    ]
